repository: ../test-repo
extensions: ['.py', '.txt', '.yaml', '.yml', '.sh', '.md', '.toml']
db_path: .database/
cache_dir: .cache/
Tools:
  - module: ICRQE.tools.tools
    tools:
      - CodebaseQATool
      - SingleDocstringTool
      - LintFileTool
      - GetFileContentsTool
      - CyclomaticComplexityTool
      - FindUsageTool
      - InstallationAndUseTool
colorscheme: 'gruvbox-dark'
debug: true
